export const FORM_VALID = "FORM_VALID";
export const AFTER_SUBMIT = "AFTER_SUBMIT";
export const FORM_HANDLER = "FORM_HANDLER";
export const FORM_FIELD_ERROR_HANDLER = "FORM_FIELD_ERROR_HANDLER";
export const FORM_FIELD_TOUCHED_HANDLER = "FORM_FIELD_TOUCHED_HANDLER";